import { internalMutation } from "./_generated/server";
import { v } from "convex/values";

export const seedExpandedWA = internalMutation({
  args: {},
  returns: v.null(),
  handler: async (ctx) => {
    const newLocations = [
      // --- YAKIMA RIVER CANYON SUB-LOCATIONS ---
      {
        name: "Umtanum Area",
        state: "Washington",
        region: "Central Washington",
        county: "Kittitas",
        description: "One of the most popular public access points in the Yakima River Canyon. Features a suspension bridge and extensive hiking trails. Collectors find jasper, agates, and occasional petrified wood in the river gravels and on the slopes.",
        coordinates: { lat: 46.8554, lng: -120.4831 },
        difficulty: 2,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "Public (BLM)",
        permitRequired: true,
        permitInfo: "BLM Day Use Fee or annual pass required for parking.",
        bestSeasons: ["Spring", "Summer", "Fall"],
        typicalFinds: ["Jasper", "Agate", "Petrified Wood"],
        directions: "Located about 15 miles south of Ellensburg on Hwy 821 (Canyon Road). Look for the Umtanum Recreation Area signs.",
        photos: ["https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Lmuma Creek",
        state: "Washington",
        region: "Central Washington",
        county: "Kittitas",
        description: "A BLM access area within the Yakima River Canyon. Known for hiking trails and river access where agates and jasper can be found in the gravel bars.",
        coordinates: { lat: 46.8291, lng: -120.4704 },
        difficulty: 2,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "Public (BLM)",
        permitRequired: true,
        permitInfo: "BLM Day Use Fee required.",
        bestSeasons: ["Spring", "Fall"],
        typicalFinds: ["Agate", "Jasper", "Chalcedony"],
        directions: "South of Umtanum on Canyon Road (Hwy 821).",
        photos: ["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Big Pines Recreation Area",
        state: "Washington",
        region: "Central Washington",
        county: "Kittitas",
        description: "A major canyon access point with a large campground. The river banks and nearby slopes offer good opportunities for finding agates and petrified wood fragments.",
        coordinates: { lat: 46.8028, lng: -120.4631 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Roadside",
        landStatus: "Public (BLM)",
        permitRequired: true,
        permitInfo: "BLM Day Use Fee required.",
        bestSeasons: ["Spring", "Fall", "Winter"],
        typicalFinds: ["Agate", "Petrified Wood", "Jasper"],
        directions: "Located in the heart of the Yakima River Canyon on Hwy 821.",
        photos: ["https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Roza Area",
        state: "Washington",
        region: "Central Washington",
        county: "Kittitas",
        description: "South end of the Yakima River Canyon near the Roza Dam. Popular for river access and searching gravel bars after high water events.",
        coordinates: { lat: 46.7550, lng: -120.4450 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Roadside",
        landStatus: "Public (BLM/WDFW)",
        permitRequired: true,
        permitInfo: "Discover Pass or BLM pass may be required.",
        bestSeasons: ["Fall", "Winter", "Spring"],
        typicalFinds: ["Agate", "Jasper", "Petrified Wood"],
        directions: "Follow Hwy 821 south toward Yakima. The Roza Recreation site is well-marked.",
        photos: ["https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Selah Butte",
        state: "Washington",
        region: "Central Washington",
        county: "Yakima",
        description: "The Selah area and Selah Butte offer diverse geological formations. Known among locals for petrified wood occurrences and basalt specimens.",
        coordinates: { lat: 46.7050, lng: -120.4100 },
        difficulty: 3,
        familyFriendly: false,
        roadAccessibility: 4,
        accessType: "Moderate Hike",
        landStatus: "Public (WDFW)",
        permitRequired: true,
        permitInfo: "Discover Pass required for WDFW lands.",
        bestSeasons: ["Spring", "Fall"],
        typicalFinds: ["Petrified Wood", "Jasper", "Basalt specimens"],
        directions: "East of Selah, WA. Access via various WDFW gates along canyon-facing slopes.",
        photos: ["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1000"]
      },

      // --- WESTPORT AREA (COASTAL) ---
      {
        name: "Westhaven State Park",
        state: "Washington",
        region: "Southwest Washington",
        county: "Grays Harbor",
        description: "One of the most popular and accessible beachcombing areas in Westport. Storms and winter tides regularly expose fresh agates, jasper, and sea glass.",
        coordinates: { lat: 46.9031, lng: -124.1278 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "State Park",
        permitRequired: true,
        permitInfo: "Discover Pass required for vehicle access.",
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Agate", "Jasper", "Chalcedony", "Sea glass", "Drift treasures"],
        directions: "In Westport, follow signs to the state park at the end of the peninsula near the jetty.",
        photos: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Twin Harbors Beach State Park",
        state: "Washington",
        region: "Southwest Washington",
        county: "Grays Harbor",
        description: "Expansive sandy beach with gravel beds that appear seasonally. Great for hunting beach pebbles, jasper, and occasional sea glass.",
        coordinates: { lat: 46.8700, lng: -124.1150 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "State Park",
        permitRequired: true,
        permitInfo: "Discover Pass required.",
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Agates", "Sea Glass", "Jasper", "Beach pebbles"],
        directions: "Located just south of Westport along Highway 105.",
        photos: ["https://images.unsplash.com/photo-1471922694854-ff1b63b20054?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Grayland Beach State Park",
        state: "Washington",
        region: "Southwest Washington",
        county: "Pacific",
        description: "Widely regarded as one of the better agate beaches on the south Washington coast. The ocean-polished stones here are a favorite for beginners.",
        coordinates: { lat: 46.8078, lng: -124.0950 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "State Park",
        permitRequired: true,
        permitInfo: "Discover Pass required.",
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Agates", "Jasper", "Petrified wood", "Ocean-polished stones"],
        directions: "South of Westport in Grayland, follow signs to the state park beach access.",
        photos: ["https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Cohasset Beach",
        state: "Washington",
        region: "Southwest Washington",
        county: "Grays Harbor",
        description: "Local favorite for beachcombing. Gravel beds are often exposed at low tide, revealing agates and colorful jasper.",
        coordinates: { lat: 46.8522, lng: -124.1100 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "Public Beach",
        permitRequired: false,
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Agates", "Sea glass", "Jasper"],
        directions: "Access via public pathways in the Cohasset Beach neighborhood south of Westport.",
        photos: ["https://images.unsplash.com/photo-1520942702018-0862200e6873?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Midway Beach",
        state: "Washington",
        region: "Southwest Washington",
        county: "Pacific",
        description: "A quieter beach that gets less traffic. Excellent for peaceful beachcombing and finding agates in a more secluded setting.",
        coordinates: { lat: 46.7550, lng: -124.0850 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 4,
        accessType: "Short Walk",
        landStatus: "Public Beach",
        permitRequired: false,
        bestSeasons: ["Year Round"],
        typicalFinds: ["Agates", "Sea glass", "General beachcombing"],
        directions: "Located between Grayland and North Cove. Look for the Midway Beach Road access.",
        photos: ["https://images.unsplash.com/photo-1464457312035-3d7d0e0c058e?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Damon Point",
        state: "Washington",
        region: "Southwest Washington",
        county: "Grays Harbor",
        description: "The crown jewel of coastal rockhounding. Famous for carnelian agates and diverse materials. A 4-mile round trip walk is required to reach the best areas.",
        coordinates: { lat: 46.9181, lng: -124.1150 },
        difficulty: 2,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Moderate Hike",
        landStatus: "Public/DNR",
        permitRequired: false,
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Carnelian agates", "Agates", "Chalcedony", "Jasper", "Petrified wood"],
        directions: "Located at the southeast tip of Ocean Shores. Park at the end of the road and walk out onto the spit.",
        photos: ["https://images.unsplash.com/photo-1515130220574-06ac2ff83cb1?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "North Jetty (Ocean Shores)",
        state: "Washington",
        region: "Southwest Washington",
        county: "Grays Harbor",
        description: "Powerful storm activity here often shifts the sands to reveal productive gravel deposits near the jetty rocks.",
        coordinates: { lat: 46.9322, lng: -124.1650 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "Public Beach",
        permitRequired: false,
        bestSeasons: ["Winter"],
        typicalFinds: ["Agates", "Jasper", "Chalcedony"],
        directions: "Follow Ocean Shores Blvd south to the very end near the North Jetty.",
        photos: ["https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Oyhut Area",
        state: "Washington",
        region: "Southwest Washington",
        county: "Grays Harbor",
        description: "The beaches near the Oyhut Wildlife Recreation Area produce good agates and colorful beach pebbles, especially near the mouth of the harbor.",
        coordinates: { lat: 46.9380, lng: -124.1350 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 4,
        accessType: "Short Walk",
        landStatus: "Public Beach",
        permitRequired: false,
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Agates", "Jasper", "Beach pebbles"],
        directions: "Access via the Oyhut Wildlife Recreation Area parking or nearby beach access points.",
        photos: ["https://images.unsplash.com/photo-1505118380757-91f5f5632de0?auto=format&fit=crop&q=80&w=1000"]
      },

      // --- SEQUIM AREA (OLYMPIC PENINSULA) ---
      {
        name: "Salt Creek Recreation Area",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "One of the best public-access rockhounding areas near Sequim. The cobble beaches produce colorful Olympic Poppy Jasper and agates after winter storms.",
        coordinates: { lat: 48.1656, lng: -123.7111 },
        difficulty: 2,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "County Park",
        permitRequired: false,
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Olympic Poppy Jasper", "Agates", "Jasper", "Beach stones"],
        directions: "West of Port Angeles/Sequim off Hwy 112. Follow signs to the Salt Creek County Park.",
        photos: ["https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Crescent Bay",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "Adjacent to Salt Creek, this bay features wave-polished stones and jasper. High quality material is often found after rough sea conditions.",
        coordinates: { lat: 48.1600, lng: -123.7300 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "Public Beach",
        permitRequired: false,
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Jasper", "Agates", "Beach pebbles", "Wave-polished material"],
        directions: "Access via the Salt Creek Recreation Area or public points along Crescent Beach Rd.",
        photos: ["https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Dungeness Spit",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "Long cobble stretches along the longest natural sand spit in the world. Collectors find agates and unique drift treasures during low tide walks.",
        coordinates: { lat: 48.1567, lng: -123.1117 },
        difficulty: 2,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Long Walk",
        landStatus: "Wildlife Refuge",
        permitRequired: true,
        permitInfo: "National Wildlife Refuge entrance fee applies.",
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Agates", "Beach stones", "Drift treasures"],
        directions: "North of Sequim. Follow Kitchen-Dick Road to the Dungeness Recreation Area.",
        photos: ["https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Sequim Bay State Park",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "A casual collecting location with a sheltered shoreline. Good for small jaspers and occasional marine fossils.",
        coordinates: { lat: 48.0400, lng: -123.0160 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "State Park",
        permitRequired: true,
        permitInfo: "Discover Pass required.",
        bestSeasons: ["Year Round"],
        typicalFinds: ["Agates", "Small jaspers", "Marine fossils"],
        directions: "Located directly on Hwy 101 just east of Sequim.",
        photos: ["https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "John Wayne Marina Shoreline",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "Public shoreline near the marina where locals hunt for agates and jasper after winter storms.",
        coordinates: { lat: 48.0620, lng: -123.0400 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "Public/Port",
        permitRequired: false,
        bestSeasons: ["Winter"],
        typicalFinds: ["Agates", "Jasper", "Beach pebbles"],
        directions: "Located at the marina in Sequim. Public access is available along the shore.",
        photos: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Murdock Beach",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "Fossil Beach. Famous for concretions that can contain crab fossils, glendonite, and fossilized shells. One of the peninsula's unique geological sites.",
        coordinates: { lat: 48.1578, lng: -123.8650 },
        difficulty: 2,
        familyFriendly: true,
        roadAccessibility: 4,
        accessType: "Short Walk",
        landStatus: "Public (DNR)",
        permitRequired: true,
        permitInfo: "Discover Pass required for DNR access.",
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Concretions", "Crab Fossils", "Glendonite", "Agates", "Fossil shells"],
        directions: "West of Port Angeles. Access via Murdock Rd off Hwy 112.",
        photos: ["https://images.unsplash.com/photo-1464457312035-3d7d0e0c058e?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Twin Beach",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "A popular spot near Joyce for finding agates, jasper, and occasional petrified wood fragments in the shoreline gravels.",
        coordinates: { lat: 48.1630, lng: -123.9500 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "Public Beach",
        permitRequired: false,
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Agates", "Jasper", "Petrified wood"],
        directions: "Located near Joyce, WA. Access points along Hwy 112.",
        photos: ["https://images.unsplash.com/photo-1505118380757-91f5f5632de0?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Jansen Creek",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "A creek mouth location where seasonal water flow and tides deliver a fresh supply of agates and jaspers to the beach gravels.",
        coordinates: { lat: 48.2430, lng: -124.2880 },
        difficulty: 2,
        familyFriendly: false,
        roadAccessibility: 3,
        accessType: "Moderate Hike",
        landStatus: "Public Beach",
        permitRequired: false,
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Agates", "Jasper", "Creek gravels"],
        directions: "West of Joyce. Access requires navigating rougher coastal terrain near creek outlets.",
        photos: ["https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Freshwater Bay",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "Quiet county park with public shoreline access. Features extensive beach cobbles containing jasper and agates.",
        coordinates: { lat: 48.1380, lng: -123.5900 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "County Park",
        permitRequired: false,
        bestSeasons: ["Year Round"],
        typicalFinds: ["Agates", "Jasper", "Beach cobbles"],
        directions: "West of Port Angeles. Follow Freshwater Bay Road to the park.",
        photos: ["https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Pillar Point",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "A scenic point known for agates, jasper, and occasional marine fossils embedded in the shoreline rocks.",
        coordinates: { lat: 48.2150, lng: -124.1100 },
        difficulty: 2,
        familyFriendly: true,
        roadAccessibility: 4,
        accessType: "Short Walk",
        landStatus: "Public (DNR/County)",
        permitRequired: true,
        permitInfo: "Discover Pass required for DNR site access.",
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Agates", "Jasper", "Marine fossils", "Beach stones"],
        directions: "Located along Hwy 112 between Joyce and Clallam Bay.",
        photos: ["https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&q=80&w=1000"]
      }
    ];

    for (const location of newLocations) {
      const existing = await ctx.db
        .query("locations")
        .withIndex("by_state", (q) => q.eq("state", "Washington"))
        .filter((q) => q.eq(q.field("name"), location.name))
        .first();

      if (!existing) {
        await ctx.db.insert("locations", {
          ...location,
          numVisits: 0,
          numFinds: 0,
          numTripLogs: 0,
          avgDifficulty: location.difficulty,
          avgAccess: location.roadAccessibility,
        });
      }
    }
    return null;
  }
});
