import { internalMutation } from "./_generated/server";
import { v } from "convex/values";

export const seedMassiveWA = internalMutation({
  args: {},
  returns: v.null(),
  handler: async (ctx) => {
    const locations = [
      // --- OLYMPIC PENINSULA: NEAH BAY / OZETTE ---
      {
        name: "Cape Flattery",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "Northwesternmost point in the contiguous United States. Stunning sea cliffs and caves. The trail overlooks the meeting point of the Pacific Ocean and Strait of Juan de Fuca.",
        geology: "Massive sea cliffs, sea caves, offshore sea stacks, and Tatoosh Island.",
        coolFacts: "Located on Makah Tribal land. A Makah Recreation Permit is required. Westernmost point in the lower 48 if you count the sea stacks!",
        coordinates: { lat: 48.3831, lng: -124.7131 },
        difficulty: 2,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "Makah Tribal Land",
        permitRequired: true,
        permitInfo: "Makah Recreation Permit required (available in Neah Bay).",
        bestSeasons: ["Summer", "Fall", "Spring"],
        typicalFinds: ["Beach agates", "Jasper", "Wave-polished basalt", "Marine fossils", "Sea glass"],
        photos: ["https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Shi Shi Beach",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "A dynamic coastal system with dramatic sea stacks and arches. Home to the famous Point of the Arches sea stack complex.",
        geology: "Dynamic coastal beach system with sea stacks, arches, tidal channels, and active erosion.",
        coolFacts: "Storms can dramatically rearrange the beach and expose new material. A Makah Recreation Permit is required for access through tribal land.",
        coordinates: { lat: 48.2750, lng: -124.6750 },
        difficulty: 4,
        familyFriendly: true,
        roadAccessibility: 4,
        accessType: "Long Hike",
        landStatus: "Makah Tribal / National Park",
        permitRequired: true,
        permitInfo: "Makah Recreation Permit required.",
        bestSeasons: ["Spring", "Summer", "Fall"],
        typicalFinds: ["Agates", "Jasper", "Chalcedony", "Petrified wood", "Beach cobbles"],
        photos: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Point of the Arches",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "One of the most dramatic sea stack formations in Washington. Best explored at low tide.",
        geology: "Natural arches, tide pools, and sea caves created by relentless Pacific wave action.",
        coolFacts: "Features spectacular tidepooling and photography opportunities. Part of the Olympic National Park coastline.",
        coordinates: { lat: 48.2450, lng: -124.6850 },
        difficulty: 4,
        familyFriendly: false,
        roadAccessibility: 4,
        accessType: "Long Hike",
        landStatus: "National Park",
        permitRequired: true,
        permitInfo: "National Park entrance fee/pass required.",
        bestSeasons: ["Summer", "Fall"],
        typicalFinds: ["Agates", "Jasper", "Marine-worn cobbles"],
        photos: ["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Hobuck Beach",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "One of the easiest-access beaches in the Neah Bay area and often productive after winter storms.",
        geology: "Long exposed beach receiving material from Pacific storms.",
        coolFacts: "Popular for surfing and beachcombing. Close to Neah Bay amenities.",
        coordinates: { lat: 48.3300, lng: -124.6650 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "Makah Tribal Land",
        permitRequired: true,
        permitInfo: "Makah Recreation Permit required.",
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Agates", "Jasper", "Sea glass", "Drift treasures"],
        photos: ["https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Makah Bay Beaches",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "Excellent location for observing the geologic forces shaping the Olympic Coast.",
        geology: "Marine terraces and wave-cut platforms formed by uplift and coastal erosion.",
        coolFacts: "Provides a window into the tectonic history of the region.",
        coordinates: { lat: 48.3150, lng: -124.6600 },
        difficulty: 2,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "Makah Tribal Land",
        permitRequired: true,
        permitInfo: "Makah Recreation Permit required.",
        bestSeasons: ["Year Round"],
        typicalFinds: ["Agates", "Jasper", "Basalt cobbles", "Sea glass"],
        photos: ["https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Cape Alava",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "Westernmost point in the contiguous United States. Part of the Olympic Coast's intensely folded and faulted geology.",
        geology: "Rugged coastline with sea stacks and uplifted marine deposits.",
        coolFacts: "Near the famous Ozette archaeological site where a Makah village was preserved by a mudslide.",
        coordinates: { lat: 48.1659, lng: -124.7317 },
        difficulty: 3,
        familyFriendly: true,
        roadAccessibility: 4,
        accessType: "Moderate Hike",
        landStatus: "Olympic National Park",
        permitRequired: true,
        permitInfo: "National Park entrance fee/pass required.",
        bestSeasons: ["Summer", "Fall"],
        typicalFinds: ["Agates", "Jasper", "Driftwood", "Marine-worn cobbles"],
        photos: ["https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Murdock Beach",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "One of Washington's most famous fossil beaches. Fossil-bearing concretions are common.",
        geology: "Fossils erode from the Pysht Formation (17–24 million years old). Evidence of ancient methane seeps.",
        coolFacts: "Famous for glendonite pseudomorphs and fossil crabs.",
        coordinates: { lat: 48.1500, lng: -123.8800 },
        difficulty: 2,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "County Park / DNR",
        permitRequired: false,
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Fossils", "Concretions", "Glendonite", "Agates", "Orbicular jasper"],
        photos: ["https://images.unsplash.com/photo-1505242844900-ed99ca970928?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Hoko River",
        state: "Washington",
        region: "Olympic Peninsula",
        county: "Clallam",
        description: "Famous among paleontologists for fossil crabs and marine life preserved in ancient ocean-floor sediments.",
        geology: "Exposures of the Hoko River Formation, a Late Eocene deep-marine fan deposit.",
        coolFacts: "The river carries material from the deep geological past directly to the accessible bank.",
        coordinates: { lat: 48.2833, lng: -124.3667 },
        difficulty: 3,
        familyFriendly: false,
        roadAccessibility: 4,
        accessType: "Moderate Hike",
        landStatus: "Public / DNR",
        permitRequired: true,
        permitInfo: "Discover Pass usually required for DNR land.",
        bestSeasons: ["Summer", "Fall"],
        typicalFinds: ["Fossils", "Fossil crabs", "Agates", "River-polished stones"],
        photos: ["https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Tolmie State Park",
        state: "Washington",
        region: "Puget Sound",
        county: "Thurston",
        description: "Nisqually Reach shoreline shaped by glacial deposits and Puget Sound wave action.",
        geology: "Glacial outwash and till deposits providing a variety of rock types.",
        coolFacts: "One of the closest public beaches to Olympia with miles of gravel to explore during low tide.",
        coordinates: { lat: 47.1235, lng: -122.7935 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "State Park",
        permitRequired: true,
        permitInfo: "Discover Pass required.",
        bestSeasons: ["Winter", "Spring"],
        typicalFinds: ["Agates", "Jasper", "Quartz", "Sea glass"],
        photos: ["https://images.unsplash.com/photo-1520942702018-0862200e6873?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Mima Mounds",
        state: "Washington",
        region: "Puget Sound",
        county: "Thurston",
        description: "One of the strangest geological landscapes in North America. Strictly observation.",
        geology: "Hundreds of mysterious earthen mounds whose origin remains debated. Possibly glacial, periglacial, or even animal-made.",
        coolFacts: "Scientists still debate exactly how the mounds formed. A true geological enigma.",
        coordinates: { lat: 46.8900, lng: -123.0500 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "Natural Area Preserve",
        permitRequired: true,
        permitInfo: "Discover Pass required. NO COLLECTING.",
        bestSeasons: ["Spring", "Fall"],
        typicalFinds: ["Geological Insight"],
        photos: ["https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Monte Cristo Area",
        state: "Washington",
        region: "Cascades",
        county: "Snohomish",
        description: "One of Washington's most famous historic mining districts. The ghost town remains a popular destination.",
        geology: "Mineralized veins containing gold, silver, copper, lead, and zinc.",
        coolFacts: "Once a bustling mining community. Many historic structures and mine workings still visible (stay out of mines!).",
        coordinates: { lat: 47.9850, lng: -121.3950 },
        difficulty: 4,
        familyFriendly: false,
        roadAccessibility: 3,
        accessType: "Long Hike",
        landStatus: "Public (USFS)",
        permitRequired: false,
        bestSeasons: ["Summer", "Early Fall"],
        typicalFinds: ["Quartz crystals", "Pyrite", "Chalcopyrite", "Galena", "Silver-bearing minerals"],
        photos: ["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Stillaguamish River (Verlot)",
        state: "Washington",
        region: "Cascades",
        county: "Snohomish",
        description: "The Stillaguamish watershed is famous for nephrite jade discoveries.",
        geology: "River gravels concentrate material from diverse Cascade foothill and alpine sources.",
        coolFacts: "Nephrite jade here usually occurs as river cobbles rather than bedrock outcrops.",
        coordinates: { lat: 48.0900, lng: -121.7800 },
        difficulty: 2,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Short Walk",
        landStatus: "Public (USFS)",
        permitRequired: false,
        bestSeasons: ["Late Summer", "Fall"],
        typicalFinds: ["Nephrite Jade", "Jasper", "Quartz", "River-polished stones"],
        photos: ["https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&q=80&w=1000"]
      },
      {
        name: "Concrete Limestone Deposits",
        state: "Washington",
        region: "Cascades",
        county: "Skagit",
        description: "Large limestone bodies in a region otherwise dominated by volcanic and metamorphic rocks.",
        geology: "Unique limestone deposits that supported major cement plants for decades.",
        coolFacts: "These deposits led directly to the creation of the town of Concrete.",
        coordinates: { lat: 48.5410, lng: -121.7470 },
        difficulty: 1,
        familyFriendly: true,
        roadAccessibility: 5,
        accessType: "Roadside",
        landStatus: "Public / Mixed",
        permitRequired: false,
        bestSeasons: ["Year Round"],
        typicalFinds: ["Limestone", "Fossils (Occasional)"],
        photos: ["https://images.unsplash.com/photo-1525875975471-999f65706a10?auto=format&fit=crop&q=80&w=1000"]
      }
    ];

    for (const location of locations) {
      const existing = await ctx.db
        .query("locations")
        .withIndex("by_name", (q) => q.eq("name", location.name))
        .first();

      if (existing) {
        await ctx.db.patch(existing._id, {
          ...location,
          // Don't overwrite aggregates if they exist
          numVisits: existing.numVisits ?? 0,
          numFinds: existing.numFinds ?? 0,
          numTripLogs: existing.numTripLogs ?? 0,
          avgDifficulty: existing.avgDifficulty ?? location.difficulty,
          avgAccess: existing.avgAccess ?? location.roadAccessibility,
        });
      } else {
        await ctx.db.insert("locations", {
          ...location,
          numVisits: 0,
          numFinds: 0,
          numTripLogs: 0,
          avgDifficulty: location.difficulty,
          avgAccess: location.roadAccessibility,
        });
      }
    }
    return null;
  }
});
