/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityLayoutRouteImport } from './routes/_community-layout'
import { Route as CommunityLayoutIndexRouteImport } from './routes/_community-layout/index'
import { Route as MineralsMineralIdRouteImport } from './routes/minerals/$mineralId'
import { Route as LocationsLocationIdRouteImport } from './routes/locations/$locationId'
import { Route as CommunityLayoutProfileRouteImport } from './routes/_community-layout/profile'
import { Route as CommunityLayoutJobsRouteImport } from './routes/_community-layout/jobs'
import { Route as CommunityLayoutExploreRouteImport } from './routes/_community-layout/explore'
import { Route as CommunityLayoutCommunityRouteImport } from './routes/_community-layout/community'
import { Route as CommunityLayoutClassifiedsRouteImport } from './routes/_community-layout/classifieds'
import { Route as CommunityLayoutChatIndexRouteImport } from './routes/_community-layout/chat/index'
import { Route as CommunityLayoutChatRoomSlugRouteImport } from './routes/_community-layout/chat/$roomSlug'

const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityLayoutRoute = CommunityLayoutRouteImport.update({
  id: '/_community-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityLayoutIndexRoute = CommunityLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityLayoutRoute,
} as any)
const MineralsMineralIdRoute = MineralsMineralIdRouteImport.update({
  id: '/minerals/$mineralId',
  path: '/minerals/$mineralId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLocationIdRoute = LocationsLocationIdRouteImport.update({
  id: '/locations/$locationId',
  path: '/locations/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityLayoutProfileRoute = CommunityLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CommunityLayoutRoute,
} as any)
const CommunityLayoutJobsRoute = CommunityLayoutJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => CommunityLayoutRoute,
} as any)
const CommunityLayoutExploreRoute = CommunityLayoutExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => CommunityLayoutRoute,
} as any)
const CommunityLayoutCommunityRoute =
  CommunityLayoutCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => CommunityLayoutRoute,
  } as any)
const CommunityLayoutClassifiedsRoute =
  CommunityLayoutClassifiedsRouteImport.update({
    id: '/classifieds',
    path: '/classifieds',
    getParentRoute: () => CommunityLayoutRoute,
  } as any)
const CommunityLayoutChatIndexRoute =
  CommunityLayoutChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => CommunityLayoutRoute,
  } as any)
const CommunityLayoutChatRoomSlugRoute =
  CommunityLayoutChatRoomSlugRouteImport.update({
    id: '/chat/$roomSlug',
    path: '/chat/$roomSlug',
    getParentRoute: () => CommunityLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof CommunityLayoutIndexRoute
  '/auth': typeof AuthRoute
  '/guide': typeof GuideRoute
  '/classifieds': typeof CommunityLayoutClassifiedsRoute
  '/community': typeof CommunityLayoutCommunityRoute
  '/explore': typeof CommunityLayoutExploreRoute
  '/jobs': typeof CommunityLayoutJobsRoute
  '/profile': typeof CommunityLayoutProfileRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/minerals/$mineralId': typeof MineralsMineralIdRoute
  '/chat/$roomSlug': typeof CommunityLayoutChatRoomSlugRoute
  '/chat/': typeof CommunityLayoutChatIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/guide': typeof GuideRoute
  '/classifieds': typeof CommunityLayoutClassifiedsRoute
  '/community': typeof CommunityLayoutCommunityRoute
  '/explore': typeof CommunityLayoutExploreRoute
  '/jobs': typeof CommunityLayoutJobsRoute
  '/profile': typeof CommunityLayoutProfileRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/minerals/$mineralId': typeof MineralsMineralIdRoute
  '/': typeof CommunityLayoutIndexRoute
  '/chat/$roomSlug': typeof CommunityLayoutChatRoomSlugRoute
  '/chat': typeof CommunityLayoutChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_community-layout': typeof CommunityLayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/guide': typeof GuideRoute
  '/_community-layout/classifieds': typeof CommunityLayoutClassifiedsRoute
  '/_community-layout/community': typeof CommunityLayoutCommunityRoute
  '/_community-layout/explore': typeof CommunityLayoutExploreRoute
  '/_community-layout/jobs': typeof CommunityLayoutJobsRoute
  '/_community-layout/profile': typeof CommunityLayoutProfileRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/minerals/$mineralId': typeof MineralsMineralIdRoute
  '/_community-layout/': typeof CommunityLayoutIndexRoute
  '/_community-layout/chat/$roomSlug': typeof CommunityLayoutChatRoomSlugRoute
  '/_community-layout/chat/': typeof CommunityLayoutChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/guide'
    | '/classifieds'
    | '/community'
    | '/explore'
    | '/jobs'
    | '/profile'
    | '/locations/$locationId'
    | '/minerals/$mineralId'
    | '/chat/$roomSlug'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/guide'
    | '/classifieds'
    | '/community'
    | '/explore'
    | '/jobs'
    | '/profile'
    | '/locations/$locationId'
    | '/minerals/$mineralId'
    | '/'
    | '/chat/$roomSlug'
    | '/chat'
  id:
    | '__root__'
    | '/_community-layout'
    | '/auth'
    | '/guide'
    | '/_community-layout/classifieds'
    | '/_community-layout/community'
    | '/_community-layout/explore'
    | '/_community-layout/jobs'
    | '/_community-layout/profile'
    | '/locations/$locationId'
    | '/minerals/$mineralId'
    | '/_community-layout/'
    | '/_community-layout/chat/$roomSlug'
    | '/_community-layout/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CommunityLayoutRoute: typeof CommunityLayoutRouteWithChildren
  AuthRoute: typeof AuthRoute
  GuideRoute: typeof GuideRoute
  LocationsLocationIdRoute: typeof LocationsLocationIdRoute
  MineralsMineralIdRoute: typeof MineralsMineralIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_community-layout': {
      id: '/_community-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CommunityLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_community-layout/': {
      id: '/_community-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CommunityLayoutIndexRouteImport
      parentRoute: typeof CommunityLayoutRoute
    }
    '/minerals/$mineralId': {
      id: '/minerals/$mineralId'
      path: '/minerals/$mineralId'
      fullPath: '/minerals/$mineralId'
      preLoaderRoute: typeof MineralsMineralIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$locationId': {
      id: '/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof LocationsLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_community-layout/profile': {
      id: '/_community-layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof CommunityLayoutProfileRouteImport
      parentRoute: typeof CommunityLayoutRoute
    }
    '/_community-layout/jobs': {
      id: '/_community-layout/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof CommunityLayoutJobsRouteImport
      parentRoute: typeof CommunityLayoutRoute
    }
    '/_community-layout/explore': {
      id: '/_community-layout/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof CommunityLayoutExploreRouteImport
      parentRoute: typeof CommunityLayoutRoute
    }
    '/_community-layout/community': {
      id: '/_community-layout/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityLayoutCommunityRouteImport
      parentRoute: typeof CommunityLayoutRoute
    }
    '/_community-layout/classifieds': {
      id: '/_community-layout/classifieds'
      path: '/classifieds'
      fullPath: '/classifieds'
      preLoaderRoute: typeof CommunityLayoutClassifiedsRouteImport
      parentRoute: typeof CommunityLayoutRoute
    }
    '/_community-layout/chat/': {
      id: '/_community-layout/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof CommunityLayoutChatIndexRouteImport
      parentRoute: typeof CommunityLayoutRoute
    }
    '/_community-layout/chat/$roomSlug': {
      id: '/_community-layout/chat/$roomSlug'
      path: '/chat/$roomSlug'
      fullPath: '/chat/$roomSlug'
      preLoaderRoute: typeof CommunityLayoutChatRoomSlugRouteImport
      parentRoute: typeof CommunityLayoutRoute
    }
  }
}

interface CommunityLayoutRouteChildren {
  CommunityLayoutClassifiedsRoute: typeof CommunityLayoutClassifiedsRoute
  CommunityLayoutCommunityRoute: typeof CommunityLayoutCommunityRoute
  CommunityLayoutExploreRoute: typeof CommunityLayoutExploreRoute
  CommunityLayoutJobsRoute: typeof CommunityLayoutJobsRoute
  CommunityLayoutProfileRoute: typeof CommunityLayoutProfileRoute
  CommunityLayoutIndexRoute: typeof CommunityLayoutIndexRoute
  CommunityLayoutChatRoomSlugRoute: typeof CommunityLayoutChatRoomSlugRoute
  CommunityLayoutChatIndexRoute: typeof CommunityLayoutChatIndexRoute
}

const CommunityLayoutRouteChildren: CommunityLayoutRouteChildren = {
  CommunityLayoutClassifiedsRoute: CommunityLayoutClassifiedsRoute,
  CommunityLayoutCommunityRoute: CommunityLayoutCommunityRoute,
  CommunityLayoutExploreRoute: CommunityLayoutExploreRoute,
  CommunityLayoutJobsRoute: CommunityLayoutJobsRoute,
  CommunityLayoutProfileRoute: CommunityLayoutProfileRoute,
  CommunityLayoutIndexRoute: CommunityLayoutIndexRoute,
  CommunityLayoutChatRoomSlugRoute: CommunityLayoutChatRoomSlugRoute,
  CommunityLayoutChatIndexRoute: CommunityLayoutChatIndexRoute,
}

const CommunityLayoutRouteWithChildren = CommunityLayoutRoute._addFileChildren(
  CommunityLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CommunityLayoutRoute: CommunityLayoutRouteWithChildren,
  AuthRoute: AuthRoute,
  GuideRoute: GuideRoute,
  LocationsLocationIdRoute: LocationsLocationIdRoute,
  MineralsMineralIdRoute: MineralsMineralIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
